server:
    port: 8082
spring:
    application:
        name: schedule-airline-service
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/AirlineScheduleDB?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
