server:
    port: 8081
spring:
    application:
        name: flight-booking-service
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/FlightBookingDB?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka