server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: flightBookingModule
          uri: lb://flight-booking-service
          predicates:
            - Path=/api/v1.0/flightBookingService/**
        - id: scheduleAirlineModule
          uri: lb://schedule-airline-service
          predicates:
            - Path=/api/v1.0/flight/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka